name: Generate Flattened Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  flatten:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🛠 Make flatten.sh executable
        run: chmod +x flatten.sh

      - name: 🧩 Run flatten.sh
        run: ./flatten.sh -i entrypoint.sh -o standalone.sh

      - name: 📦 Upload flattened script as artifact
        uses: actions/upload-artifact@v4
        with:
          name: standalone-script
          path: standalone.sh
